language: cpp

install:
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo env "PATH=$PATH" cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
